<a href="https://colab.research.google.com/github/Yarkyka/MLSAF/blob/main/Homework1_pandas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**პრაქტიკული დავალება #1**
**ნიმუში:**

_ამოცანა:_ 1. შექმენით 2D მასივი და გაზარდეთ მისი თითოეული ელემენტი 10-ით.

_ამოხსნა ჩაწერეთ კოდის უჯრაში და კომენტარებიც მიუწერეთ:_
```python
import numpy as np

# შევქმნათ 2D მასივი
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# გავზარდოთ თითოეული ელემენტი 10-ით
result = arr + 10
print(result)
```

# Pandas-ის სავარჯიშოები

1. დააიმპორტეთ Pandas და შეამოწმეთ მისი ვერსია

In [1]:
import numpy as np
print(np.__version__)


1.25.2


2. შექმენით პანდას მწკრივი (Pandas Series) NumPy მასივიდან 1-დან 10-მდე

In [2]:
import numpy as np
import pandas as pd

numpy_array = np.arange(1,11)
series = pd.Series(numpy_array)

print(series)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


3. ლექსიკონების სია (dictionary list) აქციეთ DataFrame-ად


In [3]:
import pandas as pd

data = [
    {'Name': 'Mariam', 'Age': 21},
    {'Name': 'Anna', 'Age': 22},
    {'Name': 'Alex', 'Age': 28}
]

df = pd.DataFrame(data)

print(df)

     Name  Age
0  Mariam   21
1    Anna   22
2    Alex   28


4. შექმენით 2 სტრიქონიანი DataFrame, რომელიც შეიცავს a, b და c სვეტებს. ამოირჩიეთ b სვეტი


In [4]:
import pandas as pd


data = {
    'a': [1,2],
    'b': [3,4],
    'c': [5,6]
}

df = pd.DataFrame(data)

col_b = df['b']

print(col_b)

0    3
1    4
Name: b, dtype: int64


**5**. DataFrame-ს დაამატეთ ახალი d სვეტი მნიშვნელობებით [100, 200]


In [20]:
import pandas as pd
import numpy as np

data = {
    'a': [1, 2],
    'b': [3, 4],
    'c': [5, 6]
}

df = pd.DataFrame(data)

df['d'] = np.linspace(100, 200, len(df), dtype=int)

print(df)


   a  b  c    d
0  1  3  5  100
1  2  4  6  200


6. წაშალეთ c სვეტი DataFrame-დან


In [21]:
import pandas as pd

data = {
    'a': [1, 2],
    'b': [3, 4],
    'c': [5, 6]
}

df = pd.DataFrame(data)

df = df.drop('c', axis=1)

print(df)


   a  b
0  1  3
1  2  4


7. DataFrame-ის a სვეტს გადაარქვით სახელი a-დ rename მეთოდით

In [23]:
import pandas as pd

data = {
    'a': [1, 2],
    'b': [3, 4],
    'c': [5, 6]
}

df = pd.DataFrame(data)

df.rename(columns={'a':'A'}, inplace=True)

print(df)


   A  b  c
0  1  3  5
1  2  4  6



8. გაფილტრეთ DataFrame მხოლოდ იმ სტრიქონების საჩვენებლად, სადაც b > 3


In [24]:
import pandas as pd

data = {
    'a': [1, 2],
    'b': [3, 4],
    'c': [5, 6]
}

df = pd.DataFrame(data)

filtered_df = df[df['b']>3]

print(filtered_df)

   a  b  c
1  2  4  6


9. შექმენით DataFrame ცარიელი მნიშვნელობებით და შეავსეთ 0-ებით


In [25]:
import pandas as pd
import numpy as np

df_empty = pd.DataFrame(np.nan, index=range(3), columns=['A', 'B', 'C'])

df_filled = df_empty.fillna(0)

print("DataFrame with empty values:")
print(df_empty)

print("\nDataFrame filled with zeros:")
print(df_filled)


DataFrame with empty values:
    A   B   C
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN

DataFrame filled with zeros:
     A    B    C
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0


10. სტრიქონების ინდექსი (df.index) აქციეთ DataFrame-ის სვეტად


In [26]:
import pandas as pd

data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}

df = pd.DataFrame(data)

df.reset_index(inplace=True)

print(df)


   index  A  B  C
0      0  1  4  7
1      1  2  5  8
2      2  3  6  9


11. შექმენით DataFrame a, b, c, d სვეტებით, სადაც b სვეტს ექნება ტექსტური მნიშვნელობები, ხოლო დანარჩენებს - რიცხვითი. გამოთვალეთ რიცხვითი ველების საშუალო და დააჯგუფეთ b სვეტით

In [28]:
import pandas as pd

data = {
    'a': [1, 2, 3, 4],
    'b': ['text1', 'text2', 'text1', 'text3'],
    'c': [5, 6, 7, 8],
    'd': [9, 10, 11, 12]
}

df = pd.DataFrame(data)

average_grouped = df.groupby('b').mean()

print(average_grouped)


         a    c     d
b                    
text1  2.0  6.0  10.0
text2  2.0  6.0  10.0
text3  4.0  8.0  12.0



12. დაალაგეთ (დაასორტირეთ) DataFrame b სვეტის მიხედვით კლებადი თანმიმდევრობით


In [29]:
import pandas as pd

data = {
    'a': [1, 2, 3, 4],
    'b': ['text1', 'text2', 'text1', 'text3'],
    'c': [5, 6, 7, 8],
    'd': [9, 10, 11, 12]
}

df = pd.DataFrame(data)

sorted_df = df.sort_values(by='b', ascending=False)

print(sorted_df)

   a      b  c   d
3  4  text3  8  12
1  2  text2  6  10
0  1  text1  5   9
2  3  text1  7  11


13. მოცემულია ლექსიკონი
```python
data = {
    'a': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
    'b': ['one', 'one', 'two', 'two', 'one', 'one'],
    'd': [1, 2, 3, 4, 5, 6]
}
```
data აქციეთ DataFrame-ად და შექმენით კრებსითი ცხრილი (pivot table) pivot_table მეთოდით, სადაც a იქნება ინდექსი, b - მაჯგუფებელი სვეტი, d - სვეტი, რომლის აგრეგირებაც გვინდა. აგრეგაციიფ ფუნქციებად გამოიყენეთ 'min', 'max', 'sum', 'mean'.


In [30]:
import pandas as pd

data = {
'a': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
'b': ['one', 'one', 'two', 'two', 'one', 'one'],
'd': [1, 2, 3, 4, 5, 6]
}

df = pd.DataFrame(data)

pivot_table = pd.pivot_table(df, values='d', index='a', columns='b', aggfunc=['min', 'max', 'sum', 'mean'])

print(pivot_table)

    min     max     sum     mean     
b   one two one two one two  one  two
a                                    
bar   5   4   6   4  11   4  5.5  4.0
foo   1   3   2   3   3   3  1.5  3.0


14. გააერთიანეთ ორი DataFrame-ის ვერტიკალურად concat მეთოდით


In [31]:
import pandas as pd

data1 = {
    'A': [1, 2, 3],
    'B': [4, 5, 6]
}
df1 = pd.DataFrame(data1)

data2 = {
    'A': [7, 8, 9],
    'B': [10, 11, 12]
}
df2 = pd.DataFrame(data2)

merged_df = pd.concat([df1, df2], axis=0)

print(merged_df)


   A   B
0  1   4
1  2   5
2  3   6
0  7  10
1  8  11
2  9  12


15. გააერთიანეთ ორი DataFrame-ის a სვეტის მიხედვით merge მეთოდით

In [32]:
import pandas as pd

data1 = {
    'a': ['foo', 'bar', 'baz'],
    'b': [1, 2, 3]
}
df1 = pd.DataFrame(data1)

data2 = {
    'a': ['foo', 'bar', 'qux'],
    'c': [4, 5, 6]
}
df2 = pd.DataFrame(data2)

combined_df = pd.merge(df1, df2, on='a')

print(combined_df)


     a  b  c
0  foo  1  4
1  bar  2  5


16. DataFrame შეინახეთ CSV ფაილად


In [33]:
import pandas as pd

data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6]
}
df = pd.DataFrame(data)

df.to_csv('data.csv', index=False)

print("DataFrame saved as 'data.csv'")


DataFrame saved as 'data.csv'


17. წაიკითხეთ CSV ფაილი და შექმენით DataFrame

In [34]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df)


   A  B
0  1  4
1  2  5
2  3  6



18. გამოთვალეთ DataFrame-ის რიცხვითი სვეტების კორელაციის მატრიცა

In [35]:
import pandas as pd

data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}
df = pd.DataFrame(data)

correlation_matrix = df.corr()

print("Correlation Matrix:")
print(correlation_matrix)


Correlation Matrix:
     A    B    C
A  1.0  1.0  1.0
B  1.0  1.0  1.0
C  1.0  1.0  1.0


19. DataFrame-დან წაშალეთ დუბლირებული სტრიქონები


In [36]:
import pandas as pd

data = {
    'A': [1, 2, 2, 3, 4, 4],
    'B': ['a', 'b', 'b', 'c', 'd', 'd']
}
df = pd.DataFrame(data)

df_no_duplicates = df.drop_duplicates()

print("DataFrame without duplicates:")
print(df_no_duplicates)


DataFrame without duplicates:
   A  B
0  1  a
1  2  b
3  3  c
4  4  d


20. DataFrame-ის ყველა სტრიქონში კონკრეტული მნიშვნელობები ახლით ჩაანაცვლეთ


In [37]:
import pandas as pd

data = {
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'c', 'd', 'e']
}
df = pd.DataFrame(data)

df.replace({1: 10, 'b': 'x'}, inplace=True)

print("DataFrame after replacing specific values:")
print(df)


DataFrame after replacing specific values:
    A  B
0  10  a
1   2  x
2   3  c
3   4  d
4   5  e


21. ცხრილის d სვეტის ყველა ჩანაწერი აიყვანეთ კვადრატში. გამოიყენეთ lambda ფუნქცია apply მეთოდით

In [38]:
import pandas as pd

data = {
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'c', 'd', 'e'],
    'd': [2, 3, 4, 5, 6]
}
df = pd.DataFrame(data)

df['d'] = df['d'].apply(lambda x: x**2)

print("DataFrame after squaring all entries in column 'd':")
print(df)


DataFrame after squaring all entries in column 'd':
   A  B   d
0  1  a   4
1  2  b   9
2  3  c  16
3  4  d  25
4  5  e  36


22. მოცემულია ცხრილი:
```python
df = pd.DataFrame({
    'date': ['2021-01-01', '2022-02-15', '2023-03-23'],
    'event': ['New Year', 'Valentine', 'Anniversary']
})
```
date სვეტი სტრიქონების მონაცემთა ტიპიდან (string) გარდაქმენით datetime-ად. გამოიყენეთ to_datetime მეთოდი.


In [39]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2021-01-01', '2022-02-15', '2023-03-23'],
    'event': ['New Year', 'Valentine', 'Anniversary']
})

df['date'] = pd.to_datetime(df['date'])

print(df)


        date        event
0 2021-01-01     New Year
1 2022-02-15    Valentine
2 2023-03-23  Anniversary


23. მოცემულია ცხრილი:
```python
    'a': [1, 2, np.nan, 4],
    'b': [np.nan, 2, 3, 4],
    'c': [np.nan, 2, 3, np.nan]
})
```
ცხრილის თითოეულ სვეტში დათვალეთ ცარიელი ჩანაწერების რაოდენობა


In [40]:
import pandas as pd
import numpy as np

data = {
    'a': [1, 2, np.nan, 4],
    'b': [np.nan, 2, 3, 4],
    'c': [np.nan, 2, 3, np.nan]
}
df = pd.DataFrame(data)

blank_counts = df.isna().sum()

print("Number of blank entries in each column:")
print(blank_counts)


Number of blank entries in each column:
a    1
b    1
c    2
dtype: int64


24. მოცემულია ცხრილი:
```python
df = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6],
    'b': ['x', np.nan, 'y', 'z', np.nan, np.nan],  # Note the NaN value in 'b'
    'c': [0.1, 0.2, np.nan, 0.4, 0.8, 1.5]
})
```
წაშალეთ ყველა ის სტრიქონი, სადაც b სვეტში ცარიელი მნიშვნელობებია


In [41]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6],
    'b': ['x', np.nan, 'y', 'z', np.nan, np.nan],
    'c': [0.1, 0.2, np.nan, 0.4, 0.8, 1.5]
})

df_cleaned = df.dropna(subset=['b'])

print("DataFrame after deleting rows with blank values in column 'b':")
print(df_cleaned)


DataFrame after deleting rows with blank values in column 'b':
   a  b    c
0  1  x  0.1
2  3  y  NaN
3  4  z  0.4



25. მოცემულია ცხრილი:
```python
df = pd.DataFrame({
    'a': [1, 2, 3, 4],
    'd': [-1, 2, -3, 4]
})
```
d სვეტში უარყოფითი მნიშვნელობები ჩაანაცვლეთ სვეტის საშუალოთი. გამოიყენეთ apply მეთოდი


In [42]:
import pandas as pd

df = pd.DataFrame({
    'a': [1, 2, 3, 4],
    'd': [-1, 2, -3, 4]
})

column_mean = df['d'].mean()

df['d'] = df['d'].apply(lambda x: x if x >= 0 else column_mean)

print("DataFrame after replacing negative values in column 'd' with the column mean:")
print(df)


DataFrame after replacing negative values in column 'd' with the column mean:
   a    d
0  1  0.5
1  2  2.0
2  3  0.5
3  4  4.0


26. მოცემულია ცხრილი:
```python
df = pd.DataFrame({
    'A': [1, 2, 2, 3, 3, 3],
    'B': ['a', 'b', 'b', 'c', 'c', 'c'],
    'C': [True, True, False, False, True, False]
})
```
დათვალეთ თითოეული სვეტის უნიკალური მნიშვნელობები


In [44]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 2, 3, 3, 3],
    'B': ['a', 'b', 'b', 'c', 'c', 'c'],
    'C': [True, True, False, False, True, False]
})

unique_counts = df.nunique()

print("Unique values count of each column:")
print(unique_counts)


Unique values count of each column:
A    3
B    3
C    2
dtype: int64



27. მოცემულია ცხრილი:
```python
df = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6],
    'b': ['one', 'two', 'three', 'four', 'five', 'six']
})
```

აირჩიეთ სტრიქონები, სადაც a სვეტის მნიშვნელობებია 1, 3, 5


In [45]:
import pandas as pd

df = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6],
    'b': ['one', 'two', 'three', 'four', 'five', 'six']
})

selected_rows = df[df['a'].isin([1, 3, 5])]

print("Selected rows:")
print(selected_rows)


Selected rows:
   a      b
0  1    one
2  3  three
4  5   five


28. მოცემულია ცხრილი:
```python
df = pd.DataFrame({
    'a': [1, 2, 3, 4, 5],
    'b': ['A', 'B', 'C', 'D', 'E'],
    'c': [10, 20, 15, 10, 5],
    'd': [0.1, 0.2, 0.6, 0.3, 0.2]  # ეს უნდა დარანჟირდეს
})
```
შექმენით f სვეტი, როგორც d სვეტის რანგი. გამოიყენეთ rank მეთოდი


In [46]:
import pandas as pd

df = pd.DataFrame({
    'a': [1, 2, 3, 4, 5],
    'b': ['A', 'B', 'C', 'D', 'E'],
    'c': [10, 20, 15, 10, 5],
    'd': [0.1, 0.2, 0.6, 0.3, 0.2]
})

df['f'] = df['d'].rank()

print("DataFrame with column 'f' as the rank of column 'd':")
print(df)


DataFrame with column 'f' as the rank of column 'd':
   a  b   c    d    f
0  1  A  10  0.1  1.0
1  2  B  20  0.2  2.5
2  3  C  15  0.6  5.0
3  4  D  10  0.3  4.0
4  5  E   5  0.2  2.5



29. მოცემულია ცხრილი:
```python
df = pd.DataFrame({
    'a': [3, 1, 2, 4],
    'b': ['C', 'A', 'B', 'D'], #მეორეხარისხოვანი ველი რანჟირებისას
    'd': [2, 1, 2, 1]  # პრიორიტეტული ველი რანჟირებისას
})
```
დაალაგეთ ცხრილი d და b სვეტების მიხედვით ზრდადი თანმიმდევრობით

In [48]:
import pandas as pd

df = pd.DataFrame({
    'a': [3, 1, 2, 4],
    'b': ['C', 'A', 'B', 'D'],
    'd': [2, 1, 2, 1]
})

sorted_df = df.sort_values(by=['d', 'b'], ascending=True)

print("DataFrame sorted by columns 'd' and 'b' in ascending order:")
print(sorted_df)


DataFrame sorted by columns 'd' and 'b' in ascending order:
   a  b  d
1  1  A  1
3  4  D  1
2  2  B  2
0  3  C  2



30. მოცემულია ცხრილი:
```python
df = pd.DataFrame({
    'b': ['A', 'B', 'C', 'D', 'E'],
    'd': [1, np.nan, 3, np.nan, 5]  # შეიცავს ცარიელ ჩანაწერებს
})
```
შეავსეთ d სვეტის ცარიელი ჩანაწერები სვეტის მედიანით.
გამოიყენეთ fillna და median მეთოდები






















In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'b': ['A', 'B', 'C', 'D', 'E'],
    'd': [1, np.nan, 3, np.nan, 5]
})

median_d = df['d'].median()
df['d'] = df['d'].fillna(median_d)

print("DataFrame with blank entries in column 'd' filled with the column median:")
print(df)


# NumPy სავარჯიშოები


1. დააიმპორტეთ NumPy როგორც np და შეამოწმეთ ვერსია


In [49]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 1.25.2


2. შექმენით 1D (1-განზომილებიანი) მასივი 0-დან 9-მდე რიცხვებით


In [50]:
arr_1d = np.arange(10)
print("1D array:", arr_1d)

1D array: [0 1 2 3 4 5 6 7 8 9]


3. შექმენით 3x3 numpy მასივი, რომელიც შედგება მხოლოდ True-ებისგან


In [51]:
arr_true = np.ones((3, 3), dtype=bool)
print("3x3 array of Trues:\n", arr_true)

3x3 array of Trues:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4. შექმენით 1-10 მასივი და ამოიღეთ ყველა კენტი რიცხვი


In [53]:
arr_1_to_10 = np.arange(1, 11)
arr_even = arr_1_to_10[arr_1_to_10 % 2 == 0]
print("Array with even numbers only:", arr_even)

Array with even numbers only: [ 2  4  6  8 10]


5. ჩაანაცვლეთ ყველა კენტი რიცხვი 1-10 მასივში -1 მნიშვნელობით


In [54]:
arr_replaced = np.where(arr_1_to_10 % 2 != 0, -1, arr_1_to_10)
print("Array with odd numbers replaced by -1:", arr_replaced)

Array with odd numbers replaced by -1: [-1  2 -1  4 -1  6 -1  8 -1 10]


6. გარდაქმენით 1D მასივი 2-სვეტიან 2D მასივად


In [55]:
arr_2d = arr_1d.reshape(-1, 2)
print("2D array:\n", arr_2d)

2D array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


7. ვერტიკალურად დააწყვეთ ერთმანეთზე ორი მასივი a და b. გამოიყენეთ vstack მეთოდი


In [56]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8, 9],
              [10, 11, 12]])
stacked_vertical = np.vstack((a, b))
print("Stacked vertically:\n", stacked_vertical)


Stacked vertically:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


8. ჰორიზონტალურად ერთმანეთს მიუწყვეთ ორი მასივი a და b. გამოიყენეთ hstack მეთოდი


In [57]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
stacked_horizontal = np.hstack((a, b))
print("Stacked horizontally:\n", stacked_horizontal)

Stacked horizontally:
 [[1 2 5 6]
 [3 4 7 8]]



9. შექმენით 5x5 ფორმის 2D მასივი, რომელსაც აქვს განაპირა ელემენტებად აქვს 1 და შიდა ელემენტებად 0
 ```python
 array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])
```


In [58]:
arr_border_inner = np.ones((5, 5))
arr_border_inner[1:-1, 1:-1] = 0
print("2D array with border elements of 1 and inner elements of 0:\n", arr_border_inner)


2D array with border elements of 1 and inner elements of 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]



10. შექმენით 8x8 მატრიცა და შეავსეთ იგი ჭადრაკის დაფისებურად
 ```python
 array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])
 ```



In [59]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard matrix:\n", checkerboard)

Checkerboard matrix:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


11. შექმენით 30 ზომის შემთხვევითი ვექტორი და იპოვეთ საშუალო მნიშვნელობა. გამოიყენეთ random და mean მეთოდები

In [60]:
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Mean value of the random vector:", mean_value)


Mean value of the random vector: 0.5965748265001809


12. შექმენით შემდეგი მატრიცა. გამოიყენეთ diag მეთოდი
 ```python
 array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])
 ```


In [61]:
matrix = np.diag(np.arange(5))
print("Matrix created using the diag method:\n", matrix)


Matrix created using the diag method:
 [[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


13. ნორმალიზება გაუკეთეთ 5x5 შემთხვევით მატრიცას. გამოიყენეთ rand, max, min მეთოდები და ნორმალიზების ფორმულა:
 ```python
Z = (Z - Zmin)/(Zmax - Zmin)
 ```


In [62]:
random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print("Normalized random matrix:\n", normalized_matrix)


Normalized random matrix:
 [[0.72225231 0.24403302 0.18501202 0.62307396 0.66695091]
 [0.206496   0.78150237 0.83160634 0.71173629 1.        ]
 [0.         0.2240963  0.375554   0.69464859 0.23009798]
 [0.15672972 0.6179526  0.0911885  0.37855449 0.11456865]
 [0.31095389 0.9071308  0.23761659 0.33665968 0.4531841 ]]


14. გაამრავლეთ 5x3 მატრიცა 3x2 მატრიცაზე (მატრიცულად)


In [63]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
result = np.dot(matrix1, matrix2)
print("Result of matrix multiplication:\n", result)

Result of matrix multiplication:
 [[0.68278285 0.7194311 ]
 [0.47297664 0.66582118]
 [0.21762056 0.28033831]
 [0.65357288 1.05134855]
 [0.22715238 0.19273563]]


15. მოცემული 1D მასივისთვის, ახალი ობიექტის შეუქმნელად, უარყოფითი გახადეთ ყველა ელემენტი, რომელიც 3-სა და 8-ს შორისაა

In [64]:
arr = np.array([1, 4, 6, 8, 10, 3, 2, 7, 5, 9])
arr[(arr >= 3) & (arr <= 8)] *= -1
print("Modified array:", arr)


Modified array: [ 1 -4 -6 -8 10 -3  2 -7 -5  9]


 16. იპოვეთ საერთო მნიშვნელობები ორ მასივს შორის
 ```python
 Z1 = np.random.randint(0,10,10)
 Z2 = np.random.randint(0,10,10)
 ```


In [65]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
common_values = np.intersect1d(Z1, Z2)
print("Common values between Z1 and Z2:", common_values)


Common values between Z1 and Z2: [0 2 8 9]


17. შექმენით 5x5 ნულოვანი მატრიცა
 ```python
 Z = np.zeros((5,5))
 ```
 ობიექტის შეუცვლელად გარდაქმენით (transform in-place) ისეთ მატრიცად, რომლის სტრიქონების მნიშვნელობებიც მერყეობს 0-დან 4-მდე

In [66]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print("Transformed matrix:\n", Z)

Transformed matrix:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


18. არის თუ არა შემდეგი გამოსახულება ჭეშმარიტი? პასუხი დაასაბუთეთ.
 ```python
 np.sqrt(-1) == np.emath.sqrt(-1)
 ```


In [67]:
np.sqrt(-1) == np.emath.sqrt(-1)
False

<ipython-input-67-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

19. მიიღეთ გუშინდელი, დღევანდელი და ხვალინდელი თარიღები. გამოიყენეთ `datetime64` და `timedelta64` მეთოდები

In [68]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)

Yesterday's date: 2024-03-28
Today's date: 2024-03-29
Tomorrow's date: 2024-03-30


20. შექმენით მასივი, რომლის ელემენტებიც იქნება 2016 წლის ივლისის ყველა დღე. გამოიყენეთ `arange` მეთოდი და მონაცემთა ტიპი `'datetime64[D]'`

In [69]:
days_of_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("Days of July 2016:\n", days_of_july_2016)

Days of July 2016:
 ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


21. შექმენით 2D მასივი და ამოიღებთ მხოლოდ კენტი სვეტები

In [70]:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

arr_even_columns = arr_2d[:, ::2]
print("2D array with only even columns:\n", arr_even_columns)


2D array with only even columns:
 [[1 3]
 [4 6]
 [7 9]]


22. გამოთვალეთ 2D მასივის საშუალო მნიშვნელობა.


In [71]:
mean_value = np.mean(arr_2d)
print("Mean value of the 2D array:", mean_value)

Mean value of the 2D array: 5.0



23. შექმენით ორი 2D მასივი და გაამრავლეთ მათი შესაბამისი ელემენტები.

```python
import numpy as np

# შევქმნათ ორი 2D მასივი
arr1 =
arr2 =

# გავამრავლოთ მასივების ელემენტები ერთმანეთზე
result =
print(result)
```


In [72]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
result = arr1 * arr2
print("Result of element-wise multiplication:\n", result)

Result of element-wise multiplication:
 [[ 5 12]
 [21 32]]


24. შექმენით 2D მასივი და დაადგინეთ, არის თუ არა რომელიმე ელემენტი 10-ზე მეტი

In [80]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
is_greater_than_10 = np.any(arr > 10)
print("Are there any elements greater than 10 in the array?", is_greater_than_10)


Are there any elements greater than 10 in the array? False



25. შექმენით 2D მასივი და დაითვალეთ თითოეული სვეტის საშუალო მნიშვნელობა

In [79]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
mean_values = np.mean(arr, axis=0)
print("Mean value of each column:", mean_values)

Mean value of each column: [4. 5. 6.]



26. შექმენით 2D მასივი და დაბეჭდეთ ის სტრიქონები, რომელთა ერთი ელემენტი მაინც მეტია 5-ზე. გამოიყენეთ `any` მეთოდი და `axis` ოფცია.

In [78]:
arr = np.array([['a', 'b', 'c'],
                 ['d', 'e', 'f'],
                 ['g', 'h', 'i']])
strings_with_elements_greater_than_5 = arr[np.any(arr2 > 5, axis=1)]
print("Strings with at least one element greater than 5:\n", strings_with_elements_greater_than_5)


Strings with at least one element greater than 5:
 [['d' 'e' 'f']
 ['g' 'h' 'i']]


27. გამოთვალეთ 2D მასივის სტანდარტული გადახრა.
ამოხსნა:
```python
# შევქმნათ 2D მასივი
arr =
# გამოვთვალოთ მასივის სტანდარტული გადახრა
std_dev =
print("სტანდარტული გადახრა:", std_dev)
```

In [77]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
std_dev = np.std(arr)
print("Standard Deviation:", std_dev)

Standard Deviation: 2.581988897471611


28. შექმენით 2D მასივი და შეამოწმეთ, არის თუ არა ყველა ელემენტი დადებითი. გამოიყენეთ `all` მეთოდი. პასუხი დააბეჭდინეთ

In [84]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
all_positive = np.all(arr > 0)
print("Are all elements positive in the array?", all_positive)

Are all elements positive in the array? True



29. შექმენით 2D მასივი და დათვალეთ თითოეული სტრიქონის მაქსიმალური მნიშვნელობა.

In [85]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
max_values_row = np.max(arr, axis=1)
print("Maximum value of each row:", max_values_row)

Maximum value of each row: [3 6 9]



30. შექმენით 2D მასივი და გაანულეთ ყველა ელემენტი, რომელიც 5-ზე ნაკლებია.


In [86]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr = arr[arr >= 5]
print("Array with elements greater than or equal to 5:\n", arr)

Array with elements greater than or equal to 5:
 [5 6 7 8 9]
